### ISSUE TITLE
Can't login nor register

### ISSUE THREAD

**Issue by whIIx** [yangfei4/instaverse-app#1]
As titled, no response after hitting the bottom. Wondering if the backend server is still running?

**Comment by yangfei4** [comment]
Thanks for reporting this. I was using Heroku to host my backend server, but I just realized that it's limited to 550 hours/month so the server is down now. will fix it by transferring to another backend hosting.

**Comment by yangfei4** [comment]
> As titled, no response after hitting the bottom. Wondering if the backend server is still running?

it's live now. Hopefully, you should be able to play around with the site without issues.
